---
- name: Check if MySQL is already installed.
  stat: path=/etc/init.d/mysql
  register: mysql_installed

- name: Update apt cache if MySQL is not yet installed.
  apt: update_cache=yes
  when: mysql_installed.stat.exists == false

- name: specify MySQL root password
  debconf:
    name: mysql-server
    question: "{{ item }}"
    value: "{{ mysql_root_password }}"
    vtype: password
  with_items:
    - mysql-server/root_password
    - mysql-server/root_password_again
  when: mysql_installed.stat.exists == false

- name: Ensure MySQL packages are installed.
  apt: "name={{ item }} state=present"
  with_items:
  - mysql-server
  - python-mysqldb
  notify:
  - restart mysql
 

